# This is a basic workflow to help you get started with Actions

name: Breaking changes

env:
  SEEKRET_API_GATEWAY_URL: play.seekret.io:443

# Controls when the workflow will run
on:
  pull_request:
    branches: ["*"]

  workflow_dispatch:

jobs:
  compare-openapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Install Seekret CLI
        run: curl -L https://github.com/seek-ret/installation/releases/download/0.28.6/install-seekret-linux-x86_64.sh | sh

      - name: Report breaking changes
        if: ${{ github.event_name }} == 'pull_request'
        run: |
          git fetch origin '${{ github.event.pull_request.base.sha }}'
          ~/.seekret/seekret spec-beta breaking-changes --github-token '${{ secrets.GITHUB_TOKEN }}' --github-pr '${{ github.event.pull_request.number }}' '${{ github.event.pull_request.base.sha }}' --no-impact
